export enum IngredientName {
    BEEF = 'BEEF',
    VEAL = 'VEAL',
    CHICKEN = 'CHICKEN',
    MOZZARELLA = 'MOZZARELLA',
    PARMESAN = 'PARMESAN',
    OLIVES = 'OLIVES',
    TOMATOES = 'TOMATOES',
    CUCUMBERS = 'CUCUMBERS',
    CHAMPIGNONS = 'CHAMPIGNONS',
    SALMON = 'SALMON',
    SHRIMPS = 'SHRIMPS',
    JALAPENO = 'JALAPENO',
}
